#!/bin/sh
set -e

# This script is for conda, test that it works.
conda --version

echo The following conda environment is active: $CONDA_PREFIX
read -p "Type yes to confirm installing RAIL in this environment: " input

if [ "$input" != "yes" ]; then
	echo Exiting...
	exit 1
fi

set -xe

# These packages should pull many important dependencies, like BLAS,
# numpy, Pillow and MPI.
conda install -y h5py
conda install -y pyyaml
conda install -y pandas
conda install -y matplotlib
conda install -y psutil
conda install -y cython
conda install -y mpi4py
conda install -y numexpr

pip install joblib
pip install scikit-learn
pip install scikit-learn-intelex
CFLAGS="-L $CONDA_PREFIX/lib -I $CONDA_PREFIX/include" pip install fitsio
CFLAGS="-O2 -DNDEBUG -std=gnu99" pip install pytdigest
pip install flexcode

# Install RAIL after all dependencies are installed
pip install pz-rail
pip install pz-rail-bpz
pip install pz-rail-flexzboost
pip install pz-rail-tpz
