#!/bin/sh
set -e

# This script is for conda, test that it works.
conda --version

echo The following conda environment is active: $CONDA_PREFIX
read -p "Type yes to confirm installing RAIL in this environment: " input

if [ "$input" != "yes" ]; then
	echo Exiting...
	exit 1
fi

set -xe

# These packages should pull many important dependencies, like BLAS,
# numpy, Pillow and MPI.
conda install -y h5py
conda install -y scikit-learn
conda install -y scikit-learn-intelex
conda install -y pyyaml
conda install -y pandas
conda install -y matplotlib
conda install -y psutil
conda install -y cython

# Deprecated sklearn package is required for pz-rail 0.98.2, remove it
# for later versions.
SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True pip install sklearn || true
CFLAGS="-L $CONDA_PREFIX/lib -I $CONDA_PREFIX/include" pip install fitsio
pip install flexcode

# Install RAIL after all dependencies are installed
pip install pz-rail
pip install pz-rail-bpz
pip install pz-rail-flexzboost
