#!/usr/bin/env python3
"""Generate photo-z estimate tables from raw data.

Usage:
    rail-estimate [options] [--] <input> <output>
    rail-estimate -h | --help
    rail-estimate --version

Options:
    -h --help   Show help text.
    --version   Show version.
    -a <name>, --algorithm=<name>  Select estimation algorithm
                                   [default: fzboost].
    -b <bins>, --bins=<bins>       Set number of bins (columns) in the resulting
                                   tables [default: 301].
    -c <file>, --calibration-file=<file>  Set the name of the calibration file
                                          [default: estimator_{algorithm}.pkl]
    -g <group>, --group=<group>    For HDF5 input, sets the group name (section)
                                   where input data is stored [default: ]
    -p <file>, --param-file=<file> Extra parameter file for the estimation
                                   algorithm.
    --column-template=<template>   Set the names of the input columns
                                   [default: mag_{band}]
    --column-template-error=<template-error>  Set the names of the input error
                                              columns [default: magerr_{band}]
    --sfd-deredden             Generate columns ending in _sfd from uncorrected
                               magnitudes (or LSST fluxes in nJy) and input ebv.
    --ebv-column=<name>        Input E(B-V) column used by --sfd-deredden
                               [default: ebv].
    --output-columns=<columns> Comma-separated input or generated columns to
                               retain with the PDFs and downstream HATS product
                               [default: ].
    --row-id-column=<name>     Input identifier column used to fingerprint row
                               identity and order [default: ].


Available algorithms: bpz, fzboost, tpz, gpz, lephare"""

from collections import namedtuple
from math import nan
from os.path import exists, splitext

import h5py
import numpy as np
import pandas as pd
from docopt import docopt
from yaml import YAMLError, safe_load

from rail_scripts import (
    VERSION_TEXT,
    abort,
    create_column_mapping_dict,
    error,
    find_data_file,
    info,
    load_user_params,
)
from rail_scripts.integrity import (
    FINGERPRINT_ALGORITHM,
    INTEGRITY_GROUP,
    row_id_fingerprint,
)
from rail_scripts.photometry import (
    copy_columns,
    materialize_sfd_columns,
    parse_column_list,
    projected_input_columns,
    table_column_names,
    table_row_count,
)

DEFAULT_ESTIMATOR = "fzboost"
RESERVED_OUTPUT_COLUMNS = {
    "objectId", "coord_ra", "coord_dec", "zmode", "zmean",
    "zmedian", "z_p16", "z_p84", "pdf",
}

Configuration = namedtuple(
    "Configuration",
    (
        "input",
        "output",
        "estimator",
        "estimator_config",
        "num_bins",
        "hdf5_group",
        "column_template",
        "column_template_error",
        "sfd_deredden",
        "ebv_column",
        "output_columns",
        "row_id_column",
        "extra_args",
    ),
)
Context = namedtuple(
    "Context", ("input", "estimator", "output_columns", "row_id_fingerprint")
)


def parse_cmdline():
    args = docopt(__doc__, version=VERSION_TEXT)

    estimator = args["--algorithm"]
    calibration_file = args["--calibration-file"].format(algorithm=estimator)
    calibration_file = find_data_file(calibration_file)
    hdf5_group = args["--group"]
    column_template = args["--column-template"]
    column_template_error = args["--column-template-error"]
    try:
        output_columns = parse_column_list(args["--output-columns"])
        collisions = sorted(RESERVED_OUTPUT_COLUMNS.intersection(output_columns))
        if collisions:
            raise ValueError(f"reserved product column names: {collisions}")
    except ValueError as err:
        error("Invalid --output-columns: %s" % err)
        abort()
    param_file = args['--param-file']

    try:
        num_bins = int(args["--bins"])
    except ValueError:
        error("Invalid number of bins: %s" % args["--bins"])
        abort()

    extra_args = {}
    if param_file:
        try:
            with open(param_file) as f:
                extra_args = safe_load(f)
        except (OSError, YAMLError) as e:
            error('Error loading parameter file: %s' % e)
            abort()

    info("Estimator algorithm: %s" % estimator)
    info("Estimator calibration file: %s" % calibration_file)
    info("Bins: %d" % num_bins)
    info('HDF5 group name: "%s"' % hdf5_group)
    info('Column template for magnitude data: "%s"' % column_template)
    info('Column template for error data: "%s"' % column_template_error)
    info("SFD dereddening: %s" % args["--sfd-deredden"])
    info('E(B-V) column: "%s"' % args["--ebv-column"])
    info("Output columns: %s" % (", ".join(output_columns) or "(none)"))
    info('Row identifier column: "%s"' % args["--row-id-column"])
    info('Extra parameter file: "%s"' % param_file)

    return Configuration(
        input=args["<input>"],
        output=args["<output>"],
        estimator=estimator,
        estimator_config=calibration_file,
        num_bins=num_bins,
        hdf5_group=hdf5_group,
        column_template=column_template,
        column_template_error=column_template_error,
        sfd_deredden=args["--sfd-deredden"],
        ebv_column=args["--ebv-column"],
        output_columns=output_columns,
        row_id_column=args["--row-id-column"],
        extra_args=extra_args,
    )


def load_slow_modules(estimator):
    global DEF_MAGLIMS, DS, Estimator, TableHandle, RailStage, parallel_config

    from rail.core.common_params import lsst_def_maglims as DEF_MAGLIMS
    from rail.core.data import TableHandle, DataStore
    from rail.core.stage import RailStage
    from joblib import parallel_config

    if estimator == "bpz":
        try:
            from rail.estimation.algos.bpz_lite import BPZ_lite as Estimator
        except ImportError:
            from rail.estimation.algos.bpz_lite import BPZliteEstimator as Estimator
    elif estimator == "fzboost":
        try:
            from rail.estimation.algos.flexzboost import FZBoost as Estimator
        except ImportError:
            from rail.estimation.algos.flexzboost import FlexZBoostEstimator as Estimator
    elif estimator == 'tpz':
        from rail.estimation.algos.tpz_lite import TPZliteEstimator as Estimator
    elif estimator == 'gpz':
        from rail.estimation.algos.gpz import GPzEstimator as Estimator
    elif estimator == 'lephare':
        from rail.estimation.algos.lephare import LephareEstimator as Estimator
    else:
        raise ValueError("Invalid estimator identifier: %s" % estimator)

    DS = DataStore()


def setup_estimator(
    output,
    estimator,
    estimator_config,
    column_template,
    column_template_error,
    extra_args,
    hdf5_group="",
    num_bins=301,
):
    all_args = {
            'name': 'estimate',
            'model': estimator_config,
            'output': output,
            'hdf5_groupname': hdf5_group,
            'nzbins': num_bins,
    }

    if estimator == 'tpz':
        all_args['nondetect_val'] = nan

    all_args.update(create_column_mapping_dict(
        column_template, column_template_error, DEF_MAGLIMS
    ))

    all_args.update(load_user_params(Estimator, estimator))

    all_args.update(extra_args)

    estimator = Estimator.make_stage(**all_args)

    return estimator


def required_estimator_columns(cfg):
    bands = "ugrizy"
    columns = [cfg.column_template.format(band=band) for band in bands]
    columns += [cfg.column_template_error.format(band=band) for band in bands]
    return columns


def load_input(file_name, required_columns=(), ebv_column="ebv"):
    # Work around KeyError exception in DS.read_file() by standardizing the
    # exception to ValueError.
    if not splitext(file_name)[1]:
        raise ValueError(
            "Input file name extension is required but missing: " '"%s"' % file_name
        )

    extension = splitext(file_name)[1].lower()
    if extension in (".parquet", ".parq", ".pq") and required_columns:
        try:
            import pyarrow.parquet as pq

            schema = pq.read_schema(file_name)
            selected = projected_input_columns(
                schema.names, required_columns, ebv_column
            )
            if not selected:
                raise ValueError("none of the required columns exist in the parquet input")
            data = pd.read_parquet(file_name, columns=selected)
            return DS.add_data("input", data, TableHandle, path=file_name)
        except (OSError, ValueError):
            raise
        except Exception as err:
            raise ValueError(f"unable to read projected parquet columns: {err}") from err

    return DS.read_file("input", TableHandle, file_name)


def prepare_input(cfg, input_handle):
    estimator_columns = required_estimator_columns(cfg)
    generated_columns = estimator_columns + list(cfg.output_columns)
    if cfg.sfd_deredden:
        materialize_sfd_columns(input_handle.data, generated_columns, cfg.ebv_column)

    fingerprint = None
    if cfg.row_id_column:
        if cfg.row_id_column not in table_column_names(input_handle.data):
            raise ValueError(
                f"row identifier column is unavailable: {cfg.row_id_column}"
            )
        fingerprint = row_id_fingerprint(input_handle.data[cfg.row_id_column])

    return copy_columns(input_handle.data, cfg.output_columns), fingerprint


def write_empty_estimate_output(output_file, estimator):
    zmin = float(estimator.config.zmin)
    zmax = float(estimator.config.zmax)
    num_bins = int(estimator.config.nzbins)
    xvals = np.linspace(zmin, zmax, num_bins, dtype=np.float64)

    with h5py.File(output_file, "w") as handle:
        meta = handle.create_group("meta")
        meta.create_dataset("xvals", data=xvals[np.newaxis, :])
        meta.create_dataset("pdf_name", data=np.asarray([b"interp"]))
        meta.create_dataset("pdf_version", data=np.asarray([0], dtype=np.int64))
        data = handle.create_group("data")
        data.create_dataset("yvals", shape=(0, num_bins), dtype=np.float64)
        ancil = handle.create_group("ancil")
        ancil.create_dataset("distribution_type", shape=(0,), dtype=np.int64)


def finalize_output(output_file, columns, row_id_column, fingerprint):
    with h5py.File(output_file, "a") as handle:
        integrity = handle.require_group(INTEGRITY_GROUP)
        integrity.attrs["complete"] = False
        if "data/yvals" not in handle:
            raise ValueError("estimator output is missing data/yvals")
        expected_rows = handle["data/yvals"].shape[0]
        if "ancillary" in handle:
            del handle["ancillary"]
        group = handle.create_group("ancillary") if columns else None
        for name, values in columns.items():
            if values.ndim != 1:
                raise ValueError(f"output column {name} is not one-dimensional")
            if len(values) != expected_rows:
                raise ValueError(
                    f"output column {name} has {len(values)} rows; expected {expected_rows}"
                )
            if name in group:
                del group[name]
            if values.dtype.kind in ("O", "U"):
                if not all(isinstance(value, (str, bytes)) for value in values):
                    raise ValueError(
                        f"output column {name} has unsupported object values"
                    )
                values = values.astype(h5py.string_dtype(encoding="utf-8"))
            group.create_dataset(name, data=values)

        integrity.attrs["row_count"] = expected_rows
        for name in (
            "row_id_column",
            "row_id_fingerprint_algorithm",
            "row_id_fingerprint",
        ):
            if name in integrity.attrs:
                del integrity.attrs[name]
        if fingerprint is not None:
            integrity.attrs["row_id_column"] = row_id_column
            integrity.attrs["row_id_fingerprint_algorithm"] = FINGERPRINT_ALGORITHM
            integrity.attrs["row_id_fingerprint"] = fingerprint
        handle.flush()
        integrity.attrs["complete"] = True
        handle.flush()


def mark_existing_output_incomplete(output_file):
    if not exists(output_file):
        return
    with h5py.File(output_file, "a") as handle:
        integrity = handle.require_group(INTEGRITY_GROUP)
        integrity.attrs["complete"] = False
        handle.flush()


def setup(cfg):
    info("Starting setup.")

    try:
        info("Loading all program modules...")
        load_slow_modules(cfg.estimator)
    except ImportError as err:
        error("Error: unable to import program modules.")
        error(err)
        abort()

    try:
        info("Configuring estimator...")
        estimator = setup_estimator(
            cfg.output,
            cfg.estimator,
            cfg.estimator_config,
            cfg.column_template,
            cfg.column_template_error,
            cfg.extra_args,
            cfg.hdf5_group,
            cfg.num_bins,
        )
    except OSError as err:
        error("Error: unable to load estimator calibration file.")
        error(err)
        abort()

    try:
        info("Loading input file...")
        required_columns = required_estimator_columns(cfg) + list(cfg.output_columns)
        if cfg.row_id_column:
            required_columns.append(cfg.row_id_column)
        _input = load_input(cfg.input, required_columns, cfg.ebv_column)
        output_columns, fingerprint = prepare_input(cfg, _input)
    except ValueError as err:
        error("Error: unable to load or prepare input data.")
        error(err)
        abort()
    except OSError as err:
        error("Error: unable to load input file.")
        error(err)
        abort()

    info("Setup done.")

    return Context(
        input=_input,
        estimator=estimator,
        output_columns=output_columns,
        row_id_fingerprint=fingerprint,
    )


def estimate(cfg, ctx):
    mark_existing_output_incomplete(cfg.output)
    info("Starting estimate.")

    with parallel_config(backend='threading', n_jobs=1):
        if table_row_count(ctx.input.data) == 0:
            info("Input has zero rows; writing an empty estimate output.")
            write_empty_estimate_output(cfg.output, ctx.estimator)
        else:
            ctx.estimator.estimate(ctx.input)

    finalize_output(
        cfg.output, ctx.output_columns, cfg.row_id_column, ctx.row_id_fingerprint
    )

    info("Estimate done.")


def main():
    cfg = parse_cmdline()
    ctx = setup(cfg)
    estimate(cfg, ctx)


if __name__ == "__main__":
    main()
