# ============================
# PART 1 — RUN PATH SETTINGS
# ============================
user_base_path: "/scratch/users/<your-user>/des_dr2_data_preparation"

# ============================
# PART 2 — RUN CONFIGURATIONS
# ============================

# --- Catalog options ---
DP_which_release: "DES_DR2"
DP_filter_by_detect_isPrimary: false
DP_is_objectId_in_the_index: false

# ============================
# INPUT CONFIGURATIONS
# ============================

# --- Input catalog paths ---
input_catalog_folder: '/data/public/des/dr2/primary/catalogs/coadd'
input_catalog_pattern: '*.fits'

# --- Selected columns from the input catalog ---
input_user_selected_cols:
  - COADD_OBJECT_ID
  - RA
  - DEC
  - MAG_AUTO_G_DERED
  - MAG_AUTO_R_DERED
  - MAG_AUTO_I_DERED
  - MAG_AUTO_Z_DERED
  - MAG_AUTO_Y_DERED
  - MAGERR_AUTO_G
  - MAGERR_AUTO_R
  - MAGERR_AUTO_I
  - MAGERR_AUTO_Z
  - MAGERR_AUTO_Y
  - EXTENDED_CLASS_COADD
  - FLAGS_I

# --- Input column name patterns ---
flux_col_pattern: null
err_col_pattern: null
mag_col_pattern: null
magerr_col_pattern: "MAGERR_AUTO_BAND"
mag_dered_col_pattern: "MAG_AUTO_BAND_DERED"

# --- ID and coordinate columns ---
id_col: "COADD_OBJECT_ID"
ra_col: "RA"
dec_col: "DEC"

# --- Magnitude bands and conversion ---
selected_bands: ["G", "R", "I", "Z", "Y"]
MAG_OFFSET: null
A_EBV: null

# ============================
# OUTPUT CONFIGURATIONS
# ============================

# --- Output options ---
DP_save_the_data: true
save_output_as: "parquet"  # options: "parquet", "csv", "hdf5"
DP_repartition_files: true
DP_target_rows_per_part: 130000

# --- Output magnitude column name customization ---
DP_personalized_final_names: true
DP_pesonalized_which_band_case: "lower_case"
DP_mag_final_name_pattern: "mag_BAND"
DP_magerr_final_name_pattern: "magerr_BAND"

# --- Magnitude and dereddening ---
DP_compute_magnitude: false
DP_compute_dereddening: false

# --- Rounding options ---
DP_round_mag: false
DP_round_mag_decimal_cases: 5
DP_round_magerr: false
DP_round_magerr_decimal_cases: 5

# --- Invalid value handling ---
DP_replace_all_mag_invalid_values: true
DP_replace_only_mag_with_invalid_magerr: false
DP_replace_all_magerr_invalid_values: false
DP_replace_only_magerr_with_invalid_mag: true
DP_cross_invalidate: false

# Use "null" if you want to replace by np.nan
DP_mag_value_to_replace: 99.0
DP_magerr_value_to_replace: 99.0

# --- Invalidity pattern ---
DP_is_nan_and_inf_invalid_for_mag: true
DP_is_nan_and_inf_invalid_for_magerr: true
DP_set_some_limit_as_invalid_for_mag: true
DP_invalid_limit_value_for_mag: 99.0
DP_set_some_limit_as_invalid_for_magerr: true
DP_invalid_limit_value_for_magerr: 99.0

# ============================
# PART 3 — CLUSTER CONFIGURATIONS
# ============================
CLUSTER_save_the_dask_jobs_info: true
CLUSTER_extra_dask_configs: false

CLUSTER_interface: "ib0"
CLUSTER_queue: "cpu"
CLUSTER_cores: 50
CLUSTER_processes: 1
CLUSTER_memory: "115GB"
CLUSTER_walltime: "01:00:00"
CLUSTER_account: "hpc-bpglsst"
CLUSTER_dask_scale_number: 26

# Extra Dask configuration options (used only if CLUSTER_extra_dask_configs = true)
CLUSTER_dask_config:
  distributed.worker.memory.target: null        
  distributed.worker.memory.spill: null       
  distributed.worker.memory.pause: null         
  distributed.worker.memory.terminate: null      
  distributed.worker.memory.recent-to-old: null   

# ============================
# PART 4 — VALIDATION CONFIGURATIONS
# ============================
DP_do_validation: true
DP_compare_with_template: false

# Compare with template configuration options (used only if DP_compare_with_template = true)
DP_template_type: null
template_path: null
template_pattern: null
template_id_col: null
template_mag_col: null

selected_bands_for_comparisson: null
template_bands_for_comparisson: null

comparisson_precision: null