# ============================
# PART 1 — RUN PATH SETTINGS
# ============================
user_base_path: "/scratch/users/<your-user>/dp02_object_data_preparation"

# ============================
# PART 2 — RUN CONFIGURATIONS
# ============================

# --- Catalog options ---
DP_which_release: "LSST_DP02"
DP_filter_by_detect_isPrimary: true
DP_is_objectId_in_the_index: true

# ============================
# INPUT CONFIGURATIONS
# ============================

# --- Input catalog paths ---
input_catalog_folder: "/data/cl/lsst/dp02/primary/catalogs/object"
input_catalog_pattern: "*.parq"

# --- Selected columns from the input catalog ---
input_user_selected_cols:
  - coord_ra
  - coord_dec
  - u_cModelFlux
  - g_cModelFlux
  - r_cModelFlux
  - i_cModelFlux
  - z_cModelFlux
  - y_cModelFlux
  - u_cModelFluxErr
  - g_cModelFluxErr
  - r_cModelFluxErr
  - i_cModelFluxErr
  - z_cModelFluxErr
  - y_cModelFluxErr
  - detect_isPrimary
  - refExtendedness
  - tract
  - patch

# --- Input column name patterns ---
flux_col_pattern: "BAND_cModelFlux"
err_col_pattern: "BAND_cModelFluxErr"
mag_col_pattern: null
magerr_col_pattern: null
mag_dered_col_pattern: null

# --- ID and coordinate columns ---
id_col: "objectId"
ra_col: "coord_ra"
dec_col: "coord_dec"

# --- Magnitude bands and conversion ---
selected_bands: ["u", "g", "r", "i", "z", "y"]
MAG_OFFSET: 31.4
A_EBV:
  u: 4.81
  g: 3.64
  r: 2.70
  i: 2.06
  z: 1.58
  y: 1.31

# ============================
# OUTPUT CONFIGURATIONS
# ============================
# --- Output options ---
DP_save_the_data: true
save_output_as: "parquet"  # options: "parquet", "csv", "hdf5"
DP_repartition_files: true
DP_target_rows_per_part: 130000

# --- Output magnitude column name customization ---
DP_personalized_final_names: true
DP_pesonalized_which_band_case: "lower_case"
DP_mag_final_name_pattern: "mag_BAND"
DP_magerr_final_name_pattern: "magerr_BAND"

# --- Magnitude and dereddening ---
DP_compute_magnitude: true
DP_compute_dereddening: true

# --- Rounding options ---
DP_round_mag: true
DP_round_mag_decimal_cases: 5
DP_round_magerr: true
DP_round_magerr_decimal_cases: 5

# --- Invalid value handling ---
DP_replace_all_mag_invalid_values: true
DP_replace_only_mag_with_invalid_magerr: false
DP_replace_all_magerr_invalid_values: true
DP_replace_only_magerr_with_invalid_mag: false
DP_cross_invalidate: true

# Use "null" if you want to replace by np.nan
DP_mag_value_to_replace: 999.0
DP_magerr_value_to_replace: 999.0

# --- Invalidity pattern ---
DP_is_nan_and_inf_invalid_for_mag: true
DP_is_nan_and_inf_invalid_for_magerr: true
DP_set_some_limit_as_invalid_for_mag: true
DP_invalid_limit_value_for_mag: 999.0
DP_set_some_limit_as_invalid_for_magerr: true
DP_invalid_limit_value_for_magerr: 999.0

# ============================
# PART 3 — CLUSTER CONFIGURATIONS
# ============================
CLUSTER_save_the_dask_jobs_info: true
CLUSTER_extra_dask_configs: false

CLUSTER_interface: "ib0"
CLUSTER_queue: "cpu"
CLUSTER_cores: 50
CLUSTER_processes: 1
CLUSTER_memory: "115GB"
CLUSTER_walltime: "01:00:00"
CLUSTER_account: "hpc-bpglsst"
CLUSTER_dask_scale_number: 26

# Extra Dask configuration options (used only if CLUSTER_extra_dask_configs = true)
CLUSTER_dask_config:
  distributed.worker.memory.target: null
  distributed.worker.memory.spill: null
  distributed.worker.memory.pause: null  
  distributed.worker.memory.terminate: null
  distributed.worker.memory.recent-to-old: null

# ============================
# PART 4 — VALIDATION CONFIGURATIONS
# ============================
DP_do_validation: true
DP_compare_with_template: true

# Compare with template configuration options (used only if DP_compare_with_template = true)
DP_template_type: "parquet"
template_path: "/data/cl/lsst/dp02/secondary/catalogs/skinny/parquet"
template_pattern: "*.parquet"
template_id_col: "objectId"
template_mag_col: "mag_BAND"

selected_bands_for_comparisson: ["u", "g", "r", "i", "z", "y"]
template_bands_for_comparisson: ["u", "g", "r", "i", "z", "y"]
comparisson_precision: 0.0001