PZ-TRAIN.YAML(5)
================
:doctype: manpage
:man source: pz-compute
:man version: 0.2.0
:man manual: LineA pz-compute Manual
:revdate: October 2024

NAME
----
pz-train.yaml - Configuration file for pz-train

DESCRIPTION
-----------
The *pz-train* program is an easy-to-use collection of scripts that allow
dispatching a batch job of a photometric redshift (PZ) algorithm calibration
process (*rail-train*) to the LineA Apollo cluster using the *slurm* scheduler.
The configuration file used by *pz-train* is described here.

The configuration file is a YAML file with a top-level mapping (dictionary). The
top-level mapping accepts a fixed list of keys that may configure slurm, the
*pz-train* chain of scripts, or *rail-train*. All the parameters are optional,
having default values, if missing. An example with the full list of parameters
follows:

    inputfile: reference1.pq
    outputfile: output1.pkl
    algorithm: fzboost
    sbatch: sbatch
    sbatch_args: -N 1 --exclusive --ntasks-per-node=1 --mem=0
    prog_batch: pz-train.batch
    param_file: fzboost-params.yaml
    lepharedir:
    lepharework:

There are some parameters that represent file or directory paths. These paths
may be relative to the working directory or absolute. They support expanding
environment variables using the Python standard library's ``expandvars()'' and
expanding user home directories with ``expanduser()'', so, for example, a path
like ``~/data/$\{DATASET}/large'' is accepted.

The description of each parameter, including the allowed Python types, follows:

inputfile: str [default: input.hdf5]::
  The input file with the reference data to be processed. The reference file
  must have both the magnitude values for the objects and their corresponding
  redshift values. This parameter supports expanding environment variables and
  user home directories.

outputfile: str::
  The output file with the calibration data to be generated by *pz-train*. The
  default template value is 'estimator_\{algorithm}.pkl'. This parameter
  supports expanding environment variables and user home directories.

algorithm: str [default: fzboost]::
  The estimation algorithm to use. Valid values are given by *rail-train*
  command-line parameter ``--algorithm''.

sbatch: str [default: sbatch]::
  The file name of the *sbatch* executable. The file must be in the executable
  search path.

sbatch_args: str | list[str]::
  The parameters passed to *sbatch* when executing *pz-compute.batch*. The
  default is: ``-N 1 --exclusive --ntasks-per-node=1 --mem=0''. The default
  value allocates a complete node for the calibration, reserving all hardware
  threads and all memory.  When changing this parameter, ``-N 1'' should be
  included, since *rail-train* currently doesn't support using multiple nodes
  for the training at once.
+
Besides the parameters passed in *sbatch* command-line, *pz-train.batch* also
  defines the following parameters:

  - (implicit): --time=16:00:00 -J pz-train -p cpu --propagate=NPROC

+
The implicit parameters may be overwritten with ``sbatch_args'', but not
  removed.

prog_batch: str [default: pz-train.batch]::
  The file name of the *pz-train.batch* script. The file must be in the
  executable search path.

param_file: str [default: None]::
  The file name of the estimator algorithm's parameter file. This is forwarded
  to *rail-train* with the ``--param-file'' command-line parameter. This
  parameter supports expanding environment variables and user home directories.

lepharedir: str | null::
  The path of the lephare-data directory. Ignored when the algorithm is not set
  to ``lephare''. This is used to set the ``$LEPHAREDIR'' environment variable.
  If neither this parameter nor the environment variables are set, then the
  default is set to '/lustre/t1/cl/lsst/pz_project/lephare-data'. To clear the
  environment variable, pass ``null''.

lepharework: str | null::
  The cache directory of the lephare algorithm. Ignored when the algorithm is
  not set to ``lephare''. This is used to set the ``$LEPHAREWORK'' environment
  variable. This path must have the name 'train' as its last component because
  the rail_lephare module overwrites it with the internal RAIL calibration stage
  name (currently set to 'train'). If this parameter is not set, *pz-compute*
  first checks that either the ``$LEPHAREWORK'' or ``$XDG_CACHE_HOME''
  environment variables are set. If any is set, they are not changed. If neither
  are, then ``$LEPHAREWORK'' is set to 'lephare-work/train'. To clear the
  environment variable, pass ``null''.

EXAMPLES
--------
A trivial example, assuming all defaults, except the algorithm (input file
called 'input.hdf5', output file called 'estimator_bpz.pkl':

    algorithm: bpz

A typical example, configuring the files and algorithm's parameters:

    algorithm: tpz
    inputfile: train_dp0.2_medium.pq
    outputfile: tpz-medium.pkl
    param_file: tpz-medium.yaml

An example that changes the slurm parameters:

    algorithm: gpz
    inputfile: ~app.photoz/data/ref/reference1.hdf5
    outputfile: $XDG_DATA_HOME/rail_estimate/estimator_gpz.pkl
    sbatch_args: -N 1 -n 1 -A hpc-lsst --time=1:00:00

Training with lephare and different directories:

    algorithm: lephare
    lepharedir: $SCRATCH/lephare-data
    lepharework: $SCRATCH/cache/lephare/train

Using custom executables for running *pz-train*:

    algorithm: fzboost
    sbatch: $SCRATCH/bin/mysbatch
    prog_batch: $SCRATCH/bin/pz-train-dev.batch

COPYRIGHT
---------
Copyright © 2024 LIneA IT. Licence MIT.

SEE ALSO
--------
*pz-compute*(1), *rail-train*(1), *sbatch*(1), *slurm*(1)
