RAIL-ESTIMATE(1)
================
:doctype: manpage
:man source: pz-compute
:man version: 0.2.0
:man manual: LineA pz-compute Manual
:revdate: September 2024

NAME
----
rail-estimate - Generate photo-z estimate tables from raw data.

SYNOPSIS
--------
*rail-estimate* [_OPTION_]... [--] _input_ _output_

*rail-estimate* *-h*|*--help*

*rail-estimate* *--version*

DESCRIPTION
-----------
The *rail-estimate* program is the main standalone script used to compute the
photometric redshift (PZ) tables. The script accepts an input file containing
magnitude data and outputs the estimated photo-z values as a probability
distribution.  Running *rail-estimate* depends on having a ``pre-trained''
calibration file generated by *rail-train* (or some other procedure to train
the algorithms).

The _input_ file may be a Parquet file, HDF5 file or any other format supported
by the LSST-DESC RAIL library. The program reads each line of the input table,
representing a single potential object in the sky and calculates an estimated
redshift for it, outputting the result as a probability distribution function
(PDF) for a possible range of redshift values. The redshift estimation for each
input line is independent from all other lines. The program writes the _output_
file as an HDF5 file containing a set of PDFs. The exact format of the output
PDFs vary with the estimation algorithm chosen but in the simple case it will be
a regular grid of redshift values as indices and their associated probabilities
as values.

The input must have a set of columns for magnitude data and magnitude errors, by
default following the templates ``mag_\{band}'' and ``magerr_\{band}'', where
the bands are the lower case letters representing the color bands ``u'', ``g'',
``r'', ``i'', ``z'' and ``y''. For hierachical input formats, the data must be,
by default, in the root section. *rail-estimate* does not support input files
containing flux data instead of using the magnitude scale. The program
*rail-preprocess-parquet* may be used for converting from flux to magnitude
scales and it also preprocesses input files in a standardized way for use with
*rail-estimate*.

The program supports multiple estimation algorithms to execute the estimation
and by default chooses the *fzboost* (FlexZBoost) algorithm. All the algorithms
depend on a calibration file, by default, having the template name
``estimator_\{algorithm}.pkl''. This file will be searched in the current
directory and then in the Freedesktop.org data directories named
``rail_scripts'', in order, as specified by XDG Base Directory Specification
(for example, '/usr/local/share/rail_estimate'). A way to generate calibration
files is using the *rail-train* program.

Option arguments are used to modify the handling of the input file, the
estimation algorithm and the output format. If multiple options with
conflicting formats appear in the command line, the initial ones are ignored and
the last ones are used. The list of options follows:

*-a* _name_, **--algorithm=**_name_::
  Select estimation algorithm. The available algorithms are: *fzboost*
  (default), *bpz*, *tpz*, *gpz* and *lephare*. Algorithm availability depends
  on the presence of their respective add-on packages to the core RAIL
  framework. Note that the *bpz* algorithm might auto-generate cached data files
  the first time it runs and its default directory is the RAIL installation
  directory.

*-b* _bins_, **--bins=**_bins_::
  Set number of bins (columns) in the resulting tables. The default is 301. This
  parameter is only meaningful for the algorithms that generate the redshift
  PDFs in the shape of a grid. Note: the number of bins may also be configured
  with a parameter file set with *-p*. If present in the file, the parameter
  will have priority over this option.

*-c* _file_, **--calibration-file=**_file_::
  Set the name of the calibration file. By default the name follows the template
  ``estimator_\{algorithm}.pkl'' and with this option, a different file name may
  be specified instead.

*-g* _group_, **--group=**_group_::
  For HDF5 input, sets the group name (section) where input data is stored. By
  default, the root group is used.

*-p* _file_, **--param-file=**_file_::
  Extra parameter file for the estimation algorithm. Individual algorithms may
  have a large amount of parameters. This option should be used to provide a
  YAML file containing a top-level dictionary with the parameters that should be
  modified from their default values. The *rail-estimate* program doesn't
  configure most algorithm parameters, relying on the defaults provided by the
  algorithms themselves. The exceptions are the number of bins, configured with
  the *-b* option and the *nondetect_val* parameter, which is set by default to
  *NaN* for the *tpz* algorithm. Source distributions of *rail-estimate* contain
  example parameter files with all the default values for certain source code
  snapshots of the estimation algorithms. If any command-line options and
  parameters in the parameter file refer to the same parameter, the ones in the
  parameter file have priority.

**--column-template=**_template_::
  Set the names of the input columns. This is a template text, by default
  ``mag_\{band}''. The color bands required are ``u'', ``g'', ``r'', ``i'',
  ``z'' and ``y'', so, for example, when setting this option to
  ``\{band}magnitue'', it will require the columns ``umagnitude'',
  ``gmagnitude'', ``rmagnitude'', etc. present in the input file.

**--column-template-error=**_template-error_::
  Set the names of the input error columns. This is a template text, by default
  ``magerr_\{band}''. The color bands required are ``u'', ``g'', ``r'', ``i'',
  ``z'' and ``y'', so, for example, when setting this option to
  ``\{band}error'', it will require the columns ``uerror'', ``gerror'',
  ``rerror'', etc. present in the input file.

*-h*, *--help*::
  Show help message instead of executing an estimation.

*--version*::
  Show program version number instead of executing an estimation.

EXAMPLES
--------
Execute an estimation using all the defaults: *fzboost* algorithm, input with
the ``mag_\{band}'' and ``magerr_\{band}'' columns, use the calibration file
``estimator_fzboost.pkl'' looking for it in the current directory and standard
search paths, output PDFs with 301 bins, all other defaults inherited from
*fzboost*:

    $ rail-estimate input1.pq output1.hdf5

Execute an estimation using a different algorithm (*tpz*):

    $ rail-estimate -a tpz input1.pq output1.hdf5

Change the input file's column names and group to estimate the example file
provided by the RAIL source distribution:

    $ rail-estimate --group=photometry --column-template=mag_\{band}_lsst \
                    --column-template-error=mag_err_\{band}_lsst \
                    test_dc2_validation_9816.hdf5 output1.hdf5

Provide a custom algorithm configuration:

    $ rail-estimate -a bpz -p custom-bpz.yaml -c custom-calibration.pkl \
                    input1.hdf5 output1.hdf5

Example configuration file for the *bpz* algorithm (use it with *-p*):

    dz: 0.01
    unobserved_val: -99.0
    columns_file: "test_bpz.columns"
    spectra_file: "CWWSB4.list"
    madau_flag: "no"
    no_prior: False
    p_min: 0.005
    gauss_kernel: 0.0
    zp_errors: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    mag_err_min: 0.005
    zmin: 0.0
    zmax: 3.0
    nzbins: 301
    nondetect_val: 99.0


EXIT STATUS
-----------
*0*::
  Success.

*1*::
  Failure.

ENVIRONMENT
-----------
The *rail-estimate* program is not directly configurable with environment
variables, but some of them have indirect effects through dependency libraries.
Relevant ones are summarized here:

*XDG_DATA_HOME*, *XDG_DATA_DIRS*::
  These variables modify the search path for the calibration files.

*OMP_NUM_THREADS*::
  This variable modifies the maximum number of threads used by estimation
  algorithms that use the OpenMP API (for example, *lephare*).

*ARROW_IO_THREADS*, *ARROW_DEFAULT_MEMORY_POOL*::
  These variables control the operation of Apache Arrow library that is used for
  working with Apache Parquet files.

FILES
-----
'estimator_\{algorithm}.pkl', '$XDG_DATA_HOME/rail_scripts/estimator_\{algorithm}.pkl'::
  The default file name template for the calibration files.

'$XDG_DATA_HOME/rail_scripts/algorithms_config'::
  The directory with example parameter files.


COPYRIGHT
---------
Copyright © 2024 LIneA IT. Licence MIT.

SEE ALSO
--------
*rail-preprocess-parquet*(1), *rail-train*(1)

A quick start tutorial document is also available in the source distribution:
'doc/rail-estimate-getting-started.md'.
