#!/usr/bin/env python3
# Transform HDF5 file to a standard structure, used by LineA.
#
# - All datasets in the root ("/") group.
# - Magnitude template name: mag_{band}.
# - Magnitude error template name: magerr_{band}.

from os.path import basename
from sys import argv

import h5py

def transform_name(name):
    return basename(name).removesuffix('_lsst').replace('mag_err', 'magerr')

def on_visit(name, obj, out):
    if isinstance(obj, h5py.Group):
        return

    out.create_dataset(transform_name(name), obj.shape, obj.dtype, obj)

def main():
    with h5py.File(argv[1], 'r') as r, h5py.File(argv[2], 'w') as w:
        r.visititems(lambda *a: on_visit(*a, w))

if __name__ == '__main__': main()
